spark.master=spark://cb4ae00-lcedt:7077
spark.executor.instances=1
spark.executor.cores=8
spark.executor.memory=10g
spark.executor.resource.gpu.amount=1
spark.task.resource.gpu.amount=0.125
spark.task.maxFailures=1
spark.sql.execution.arrow.pyspark.enabled=true
spark.python.worker.reuse=true
spark.pyspark.python=/home/rishic/anaconda3/envs/spark-dl-vllm/bin/python
spark.pyspark.driver.python=/home/rishic/anaconda3/envs/spark-dl-vllm/bin/python
spark.locality.wait=0s
spark.sql.adaptive.enabled=false
spark.sql.execution.sortBeforeRepartition=false
spark.sql.files.minPartitionNum=16